import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import type { ApiClient } from '../api-client.js';
import type { ProjectRepo, SquadContext } from '../types.js';

interface IssueByKeyResponse {
  id: string;
  key: string;
  project_id: string;
  status: string;
  title: string;
}

/** Pick the right repo for the handoff. Order of resolution:
 *  1. user passed `--repo <name>` → match by name (case-insensitive)
 *  2. issue declares `affected_repos`:
 *     - exactly one → use it (skips primary preference; the issue knows better)
 *     - more than one → ambiguous, but the choice list is restricted to those
 *  3. project has exactly one repo → use it
 *  4. project has a primary repo → use that one
 *  5. ambiguous → return null with the full repo list as choices
 */
function resolveRepo(
  repos: ProjectRepo[],
  affectedRepoIds: string[],
  explicitName?: string,
): { repo: ProjectRepo | null; ambiguous: boolean; choices: ProjectRepo[] } {
  if (repos.length === 0) return { repo: null, ambiguous: false, choices: [] };
  if (explicitName) {
    const match = repos.find((r) => r.name.toLowerCase() === explicitName.toLowerCase());
    return { repo: match ?? null, ambiguous: !match, choices: repos };
  }
  const affected = repos.filter((r) => affectedRepoIds.includes(r.id));
  if (affected.length === 1) return { repo: affected[0], ambiguous: false, choices: affected };
  if (affected.length > 1) return { repo: null, ambiguous: true, choices: affected };
  if (repos.length === 1) return { repo: repos[0], ambiguous: false, choices: repos };
  const primary = repos.find((r) => r.isPrimary);
  if (primary) return { repo: primary, ambiguous: false, choices: repos };
  return { repo: null, ambiguous: true, choices: repos };
}

function renderSquadContext(ctx: SquadContext, targetRepo: ProjectRepo): string {
  const sections: string[] = [];

  sections.push(`# Squad AI handoff — ${ctx.issue.key}: ${ctx.issue.title}`);
  sections.push('');
  sections.push(`**Project:** ${ctx.projectName} (${ctx.projectKey})`);
  if (ctx.techStack) sections.push(`**Tech stack:** ${ctx.techStack}`);
  sections.push(`**Working in repo:** ${targetRepo.name} (${targetRepo.provider})`);
  if (ctx.currentStatus) {
    const role = ctx.currentStatus.systemRole ? ` (${ctx.currentStatus.systemRole})` : '';
    sections.push(`**Current pipeline status:** ${ctx.currentStatus.name}${role}`);
  }

  if (ctx.repos.length > 1) {
    sections.push('');
    sections.push('**Other repos in this project:**');
    for (const r of ctx.repos.filter((rr) => rr.id !== targetRepo.id)) {
      sections.push(`- ${r.name} (${r.provider})`);
    }
    sections.push('_If your change touches another repo, open a PR there too — the issue closes only when **all** linked PRs merge._');
  }
  sections.push('');

  sections.push('## Description');
  sections.push(ctx.issue.description?.trim() || '_(no description)_');
  sections.push('');

  if (ctx.refinementMd?.trim()) {
    sections.push('## Refinement (PO agent)');
    sections.push(ctx.refinementMd.trim());
    sections.push('');
  }

  if (ctx.designMd?.trim()) {
    sections.push('## Design (Design agent)');
    sections.push(ctx.designMd.trim());
    sections.push('');
  }

  if (ctx.testPlanMd?.trim()) {
    sections.push('## Test plan (Test agent)');
    sections.push(ctx.testPlanMd.trim());
    sections.push('');
  }

  if (ctx.documents && ctx.documents.length > 0) {
    sections.push('## Project documents');
    for (const doc of ctx.documents) {
      sections.push(`### ${doc.docType.toUpperCase()}: ${doc.title} (v${doc.version})`);
      sections.push(doc.content.trim());
      sections.push('');
    }
  }

  sections.push('---');
  sections.push('_Generated by Squad AI · Read the sections above before writing code._');
  sections.push(`_Issue ID: ${ctx.issue.id}_`);

  return sections.join('\n');
}

export function registerSquadPickupTool(server: McpServer, client: ApiClient) {
  server.tool(
    'squad_pickup',
    'Pick up a Squad AI ticket for local development. Resolves the issue by key (e.g. PROJ-123), returns the rendered SQUAD_CONTEXT.md content for the assistant to write into the developer\'s repo, and marks the issue as in-progress in xSquad. Multi-repo defaulting: if the issue declares affected_repos and there is exactly one, it is auto-selected (overriding primary). If multiple, you must pick from those. Otherwise the primary is used. The assistant MUST write the returned markdown to `.claude/SQUAD_CONTEXT.md` in the target repo (creating the `.claude/` directory if needed) using its file-writing tool.',
    {
      issueKey: z.string().describe('Issue key, e.g. "PROJ-123". The same key shown in the xSquad UI.'),
      repo: z.string().optional().describe('Repo name when the project has more than one (e.g. "backend"). Defaults to the primary or the only one.'),
    },
    async ({ issueKey, repo }) => {
      const lookup = await client.api<IssueByKeyResponse>(
        `/api/ai/squad/issues/by-key/${encodeURIComponent(issueKey)}`,
      );

      const ctx = await client.api<SquadContext>(
        `/api/projects/${lookup.project_id}/squad/issues/${lookup.id}/context`,
      );

      // 1. Pick the right repo. Affected repos take precedence over primary
      // because the issue knows which repos it actually touches.
      const affectedIds = ctx.affectedRepoIds ?? [];
      const { repo: targetRepo, ambiguous, choices } = resolveRepo(ctx.repos, affectedIds, repo);

      if (!targetRepo && ambiguous) {
        const list = choices.map((r) => `- \`${r.name}\` (${r.provider}${r.isPrimary ? ', primary' : ''})`).join('\n');
        const reason = affectedIds.length > 1
          ? `This ticket affects ${choices.length} repos.`
          : `Project has ${ctx.repos.length} repos and no primary set.`;
        return {
          content: [{
            type: 'text' as const,
            text: [
              `⚠️ ${reason} Choose one:`,
              '',
              list,
              '',
              `Re-run with the \`repo\` argument, e.g. \`/squad-pickup ${issueKey} repo=${choices[0]?.name ?? 'backend'}\`.`,
              affectedIds.length > 1
                ? `_The issue closes only when **all** affected repos have a merged PR._`
                : '',
            ].filter(Boolean).join('\n'),
          }],
        };
      }

      if (!targetRepo) {
        return {
          content: [{
            type: 'text' as const,
            text: [
              `⚠️ ${repo ? `No repo named "${repo}" in this project.` : 'This project has no repos configured.'}`,
              '',
              `Add one in xSquad: Settings → Squad AI → Repositories.`,
            ].join('\n'),
          }],
        };
      }

      // 2. Render the brief. We do NOT write to disk here: the hosted MCP
      // has no access to the developer's filesystem, so the markdown is
      // returned in the tool result and the assistant (Claude Code) writes
      // it locally with its own file-writing tool. This works identically
      // for stdio-mode local installs.
      const markdown = renderSquadContext(ctx, targetRepo);
      const suggestedPath = `.claude/SQUAD_CONTEXT.md`;

      // 3. Mark the issue as picked up. Fail loud so the dev knows.
      let pickupNote = '🔄 Status updated → human_active, assigned to you in xSquad';
      try {
        await client.api(
          `/api/projects/${lookup.project_id}/squad/issues/${lookup.id}/pickup`,
          { method: 'POST' },
        );
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : String(err);
        pickupNote = [
          `⚠️ Could not transition the issue to in-progress automatically.`,
          `Server said: ${message}`,
          `You can still start working — just move the ticket manually in xSquad.`,
        ].join('\n');
      }

      const tokensApprox = Math.ceil(markdown.length / 4);
      const autoSelected = !repo && affectedIds.length === 1 && targetRepo.id === affectedIds[0];
      const multi = ctx.repos.length > 1
        ? `\n📦 Multi-repo project (${ctx.repos.length} repos). Issue closes only when **all** linked PRs are merged.`
        : '';
      const affectedNote = autoSelected
        ? `\n🎯 Auto-selected from affected_repos (this ticket only touches \`${targetRepo.name}\`).`
        : '';

      return {
        content: [{
          type: 'text' as const,
          text: [
            `✅ Picked up ${lookup.key}: ${lookup.title}`,
            '',
            `📁 Target repo: ${targetRepo.name} (${targetRepo.provider})`,
            `🧠 ~${tokensApprox.toLocaleString()} tokens of context (refinement, design, test plan, project docs)`,
            `${pickupNote}${multi}${affectedNote}`,
            '',
            `---`,
            `**Action required (assistant):** write the markdown below verbatim to`,
            `\`${suggestedPath}\` in the developer's current working directory (create the \`.claude/\` directory if it does not exist).`,
            `After writing, tell the developer: "context saved at .claude/SQUAD_CONTEXT.md, read it and start with the first subtask".`,
            ``,
            `<<<BEGIN SQUAD_CONTEXT.md>>>`,
            markdown,
            `<<<END SQUAD_CONTEXT.md>>>`,
          ].join('\n'),
        }],
      };
    },
  );
}
